# *** This Dockerfile is generated by KloverCloud *** #
FROM klovercloud/php-7.3.20-apache2-laravel:v1.0.1

#TEMP_APP_HOME=/home/klovercloud/tmp
WORKDIR $TEMP_APP_HOME

COPY . .
RUN mkdir -p bootstrap/cache vendor
RUN chmod +x init.sh
RUN sed -i 's/\r$//' init.sh

# install all PHP dependencies
RUN composer install --no-interaction

EXPOSE 8080

#APP_HOME=/home/klovercloud/app
WORKDIR $APP_HOME

USER klovercloud
